name: Update Readme

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
          python-version: "3.9"
          architecture: "x64"

    - name: Update Readme
      run: |-
        python generate_readme.py
        cat README.md

    - name: Load to GitHub
      run: |-
        git diff
        git config --global user.email "readmebot@walkx.org"
        git config --global user.name "Readme Bot"
        git add -A
        git commit -m "✨ feat(add): Update Readme" || exit 0
        git push

